BanPC/Controllers/CartController.cs
using MyClass.DAO;
using MyClass.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanPC.Controllers
{
    public class CartController : Controller
    {
        ProductDAO productDAO = new ProductDAO();
        UserDAO userDAO = new UserDAO();
        OrderDAO orderDAO = new OrderDAO();
        OrderDetailDAO orderDetailDAO = new OrderDetailDAO();
        XCart xcart = new  XCart();
        // GET: Cart
        public ActionResult Index()
        {
            List<CartItem> listcart = xcart.getCart();//ép kiểu
            return View("Index", listcart);
        }
        public ActionResult CartAdd(int productid)
        {
            Product product = productDAO.getRow(productid);
            CartItem cartitem = new CartItem(product.Id,product.Name,product.Image,product.Pricesale,1);
            //Add vào giỏ hàng
            List<CartItem> listcart = xcart.AddCart(cartitem);
            return RedirectToAction("Index", "Cart");
        }
        public ActionResult CartDel(int productid)
        {
            xcart.DelCart(productid);
            return RedirectToAction("Index", "Cart");
        }
        //CartUpdate
        public ActionResult CartUpdate(FormCollection form)
        {
            if (!string.IsNullOrEmpty(form["CAPNHAT"]))
            {
                var listqty = form["qty"];//1,2,3,4,5,6
                var listarr = listqty.Split(',');
                xcart.UpdateCart(listarr);
            }
            return RedirectToAction("Index", "Cart");
        }
        public ActionResult CartDelAll()
        {
            xcart.DelCart(null);
            return RedirectToAction("Index", "Cart");
        }
        public ActionResult Payment()
        {
            
            List<CartItem> listcart = xcart.getCart();//ép kiểu
            //Kiểm tra đăng nhập trang người dùng==>khách hàng
            if (Session["UserCustomer"].Equals(""))
            {
                return Redirect("~/dang-nhap");// chuyển hướng đến URL
            }
            int userid = int.Parse(Session["CustomerId"].ToString());//Mã người đăng nhập
            User user = userDAO.getRow(userid);
            ViewBag.user = user;
            return View("Payment", listcart);
        }
        public ActionResult Purchase(FormCollection field)
        {
            //Lưu thông tin vào csdl order và orderdetail 
            int userid = int.Parse(Session["CustomerId"].ToString());//Mã người đăng nhập
            User user = userDAO.getRow(userid);
            ViewBag.user = user;
            //Lấy thông tin
            String note = field["Note"];
            String ReceiverAddress = field["ReceiverAddress"];
            String ReceiverPhone = field["ReceiverPhone"];
            String ReceiverEmail = field["ReceiverEmail"];
            String ReceiverName = field["ReceiverName"];
            //Tạo đối tượng đơn hàng
            Order order = new Order();
            order.UserId = userid;
            order.Note = note;
            order.ReceiverAddress = ReceiverAddress;
            order.ReceiverPhone = ReceiverPhone;
            order.ReceiverEmail = ReceiverEmail;
            order.ReceiverName = ReceiverName;
            order.Status = 1;
            Random rd = new Random();
            order.Code = "DH" + rd.Next(0, 9) + rd.Next(0, 9) + rd.Next(0, 9) + rd.Next(0, 9);
            if(orderDAO.Insert(order)==1)
            {
                //thêm vào chi tiết đơn hàng
                List<CartItem> listcart = xcart.getCart();//ép kiểu
                foreach (CartItem cartItem in listcart) 
                {
                    OrderDetail orderdetail = new OrderDetail();
                    orderdetail.OrderId = order.Id;
                    orderdetail.ProductId = cartItem.ProductId;
                    orderdetail.Price = cartItem.Price;
                    orderdetail.Qty = cartItem.Qty;
                    orderdetail.Amount = cartItem.Amount;
                    orderDetailDAO.Insert(orderdetail);//lưu
                }
                //send email
                var strSanPham = "";
                var thanhtien = decimal.Zero;
                var TongTien = decimal.Zero;
                foreach(var sp in listcart)
                {
                    strSanPham += "<tr>";
                    strSanPham += "<td>" + sp.Name +"</td>";
                    strSanPham += "<td>" + sp.Qty +"</td>";
                    strSanPham += "<td>" + BanPC.Common.Common.FormatNumber(sp.Price,0) +"</td>";
                    strSanPham += "<tr>";
                    thanhtien += sp.Price * sp.Qty;
                }
                TongTien = thanhtien;
                string contentCustomer = System.IO.File.ReadAllText(Server.MapPath("~/Content/templates/send2.html"));
                contentCustomer = contentCustomer.Replace("{{MaDon}}", order.Code);
                contentCustomer = contentCustomer.Replace("{{SanPham}}", strSanPham);
                contentCustomer = contentCustomer.Replace("{{NgayDat}}", DateTime.Now.ToString("dd/MM/yyyy"));
                contentCustomer = contentCustomer.Replace("{{TenKhachHang}}", order.ReceiverName);
                contentCustomer = contentCustomer.Replace("{{Phone}}", order.ReceiverPhone);
                contentCustomer = contentCustomer.Replace("{{Email}}", order.ReceiverEmail);
                contentCustomer = contentCustomer.Replace("{{Diachigiaohang}}", order.ReceiverAddress);
                contentCustomer = contentCustomer.Replace("{{ThanhTien}}", BanPC.Common.Common.FormatNumber(thanhtien,0));
                contentCustomer = contentCustomer.Replace("{{TongTien}}", BanPC.Common.Common.FormatNumber(TongTien,0));
                BanPC.Common.Common.SendMail("BanPC","Don hang #"+ order.Code, contentCustomer.ToString(),order.ReceiverEmail);

                string contentAdmin = System.IO.File.ReadAllText(Server.MapPath("~/Content/templates/send1.html"));
                contentAdmin = contentAdmin.Replace("{{MaDon}}", order.Code);
                contentAdmin = contentAdmin.Replace("{{SanPham}}", strSanPham);
                contentAdmin = contentAdmin.Replace("{{NgayDat}}", DateTime.Now.ToString("dd/MM/yyyy"));
                contentAdmin = contentAdmin.Replace("{{TenKhachHang}}", order.ReceiverName);
                contentAdmin = contentAdmin.Replace("{{Phone}}", order.ReceiverPhone);
                contentAdmin = contentAdmin.Replace("{{Email}}", order.ReceiverEmail);
                contentAdmin = contentAdmin.Replace("{{Diachigiaohang}}", order.ReceiverAddress);
                contentAdmin = contentAdmin.Replace("{{ThanhTien}}", BanPC.Common.Common.FormatNumber(thanhtien, 0));
                contentAdmin = contentAdmin.Replace("{{TongTien}}", BanPC.Common.Common.FormatNumber(TongTien, 0));
                BanPC.Common.Common.SendMail("BanPC", "Đơn hàng mới #" + order.Code, contentAdmin.ToString(), ConfigurationManager.AppSettings["EmailAdmin"]);

                xcart.DelCart();
            }
            return Redirect("~/thanh-cong");
        }
        public ActionResult Success()
        {
            return View();
        }
    }
}

BanPC/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using MyClass.DAO;
using MyClass.Models;
using PagedList;

namespace BanPC.Controllers
{
    public class SiteController : Controller
    {
        private MyDBContext dBContext = new MyDBContext();
        LinkDAO linkDAO = new LinkDAO();
        ProductDAO productDAO = new ProductDAO();
        PostDAO postDAO = new PostDAO();
        CategoryDAO categoryDAO = new CategoryDAO();
        TopicDAO topicDAO = new TopicDAO();
        //URL mặc định hoặc URL bất kỳ

        // GET: Site
        public ActionResult Index(string slug = null, int? page=null)
        {
            if (slug == null)
            {
                return this.Home();
            }
            else
            {
                Link link = linkDAO.getRow(slug);
                if (link != null)
                {
                    string typelink = link.TypeLink;
                    switch (typelink)
                    {
                        case "category":
                            {
                                return this.ProductCategory(slug,  page);
                            }
                        case "topic":
                            {
                                return this.PostTopic(slug, page);
                            }
                        case "page":
                            {
                                return this.PostPage(slug);
                            }
                        default:
                            {
                                return this.Error404(slug);
                            }
                    }
                }
                else
                {
                    //slug có trong bảng product
                    Product product = productDAO.getRow(slug);
                    if (product != null)
                    {
                        return this.ProductDetail(product);
                    }  
                    else
                    {

                        Post post = postDAO.getRow(slug);
                        if(post != null)
                        {
                            return this.PostDetail(post);
                        }   
                        else
                        {
                            return this.Error404(slug);
                        }    
                    }    
                    //slug có trong bảng Post Post-type=post
                    //Slug ko có trong bảng link 
                }
            }    
        }
        //Trang chủ
        public ActionResult Home()
        {
            List<ProductInfo> productNew = productDAO.getList(8);
            ViewBag.ProductNew = productNew;
            List<Category> list = categoryDAO.getListByParentId(0);
            return View("Home", list);
        }
        public ActionResult HomeProduct(int id)
        {
            Category category = categoryDAO.getRow(id);
            ViewBag.Category = category;
            //Danh mục loại theo 3 cấp
            List<int> listcatid = new List<int>();
            listcatid.Add(id);// cấp 1
            List<Category> listcategory2 = categoryDAO.getListByParentId(id);
            if(listcategory2.Count()!=0)
            {
                foreach(var category2 in listcategory2)
                {
                    listcatid.Add(category2.Id);// cấp 2
                    List<Category> listcategory3 = categoryDAO.getListByParentId(category2.Id);
                    if (listcategory3.Count() != 0)
                    {
                        foreach (var category3 in listcategory3)
                        {
                            listcatid.Add(category3.Id);// cấp 3
                        }
                    }
                }
            }    
            List<ProductInfo> list = productDAO.getListByListCatId(listcatid, 4);
            return View("HomeProduct", list);
        }
        //Nhóm Action Product
        public ActionResult Product(int? page)
        {
            int pageNumber = page ?? 1; //Trang hiện tại
            int pageSize = 4;// số mẫu tin hiển thị 1 trang
            IPagedList<ProductInfo> list = productDAO.getList(pageSize, pageNumber);
            return View("Product", list);
        }
        public ActionResult ProductCategory(string slug, int? page)
        {
            int pageNumber = page ?? 1; //Trang hiện tại
            int pageSize = 4;// số mẫu tin hiển thị 1 trang
            Category category = categoryDAO.getRow(slug);
            ViewBag.Category = category;
            //Danh mục loại theo 3 cấp
            List<int> listcatid = new List<int>();
            listcatid.Add(category.Id);// cấp 1
            List<Category> listcategory2 = categoryDAO.getListByParentId(category.Id);
            if (listcategory2.Count() != 0)
            {
                foreach (var category2 in listcategory2)
                {
                    listcatid.Add(category2.Id);// cấp 2
                    List<Category> listcategory3 = categoryDAO.getListByParentId(category2.Id);
                    if (listcategory3.Count() != 0)
                    {
                        foreach (var category3 in listcategory3)
                        {
                            listcatid.Add(category3.Id);// cấp 3
                        }
                    }
                }
            }

            //
            IPagedList<ProductInfo> list = productDAO.getListByListCatId(listcatid, pageSize, pageNumber);
            return View("ProductCategory", list);
        }
        public ActionResult ProductDetail(Product product)
        {
            return View("ProductDetail", product);
        }
        public ActionResult Product_sale()
        {
            var item=dBContext.Products.Where(x=>x.Sale==1).Take(8).ToList();
            return View("Product_sale",item);
        }
        //Nhóm Post
        public ActionResult Post(int? page)
        {
            List<PostInfo> list = postDAO.getList("Post");
            return View("Post", list);
        }
        public ActionResult PostTopic(string slug, int? page)
        {
            Topic topic = topicDAO.getRow(slug);
            ViewBag.Topic=topic;
            List<PostInfo> list = postDAO.getListByTopicId(topic.Id, "Post", null);
            return View("PostTopic", list);
        }
        public ActionResult PostPage(string slug)
        {
            Post post = postDAO.getRow(slug,"page");
            return View("PostPage", post);
        }
        public ActionResult PostDetail(Post post)
        {
            ViewBag.ListOther = postDAO.getListByTopicId(post.TopicId,"Post",post.Id);
            return View("PostDetail", post);
        }
        //hàm lỗi
        public ActionResult Error404(string slug)
        {
            return View("Error404");
        }
    }
}

BanPC/Views/Cart/Index.cshtml
@model IEnumerable<CartItem>
@{
    ViewBag.Title = "Giỏ Hàng";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<section class="maincontent clearfix my-2">
    <div class="container">
        <div class="row">
            <div class="content_top">
                <div class="heading" style="font-weight: bold;">
                    <h3>Giỏ Hàng</h3>
                </div>
            </div>
            @if (Model != null)
            {
                using (Html.BeginForm("CartUpdate", "Cart", FormMethod.Post))
                {
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Mã SP</th>
                                <th style="width:80px;">Hình</th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Số lượng</th>
                                <th>Thành tiền</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ decimal tongtien = 0;}
                            @foreach (var cart in Model)
                            {
                                <tr>
                                    <td>@cart.ProductId</td>
                                    <td><img src="~/Public/images/products/@cart.Img" alt="@cart.Name" /></td>
                                    <td>@cart.Name</td>
                                    <td>@cart.Price VNĐ</td>
                                    <td><input name="qty" value="@cart.Qty" type="number" min="1" /></td>
                                    <td class="text-end">@string.Format("{0:0,0}", cart.Amount) VNĐ</td>
                                    <td class="text-center">
                                        <a class="text-danger" href="@Url.Action("CartDel", "Cart", new {productid = cart.ProductId})">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                                tongtien += cart.Amount;
                            }
                            <tr>
                                <td colspan="4">
                                    <a href="@Url.Action("Index","Site")" class="btn btn-sm btn-success">Mua thêm sản phẩm</a>
                                    <input class="btn btn-sm btn-info" name="CAPNHAT" value="Cập nhật" type="submit" />
                                    <a href="@Url.Action("CartDelAll","Cart")" class="btn btn-sm btn-danger">Xóa đơn hàng</a>
                                    <a href="~/thanh-toan" class="btn btn-sm btn-success">Thanh toán</a>
                                </td>
                                <td class="text-end">Thành tiền</td>
                                <td colspan="2" class="text-end">@string.Format("{0:0,0}", tongtien) VNĐ</td>
                            </tr>
                        </tbody>
                    </table>

                }
            }
            else
            {

                <h1 class="my-2">Chưa có sản phẩm trong giỏ hàng</h1>
            }
        </div>
    </div>
</section>

BanPC/Views/Cart/Payment.cshtml
@model IEnumerable<CartItem>

@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@{ 
    var user = ViewBag.user;
}
@using (Html.BeginForm("Purchase", "Cart", FormMethod.Post))
{
<section class="maincontent clearfix my-2">
    <div class="container">
        <div class="row">
            <div class="content_top">
                <div class="heading" style="font-weight: bold;">
                    <h3>Thanh Toán</h3>
                </div>
            </div>
            <div class="row my-2">
                <div class="col-md-9">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Mã SP</th>
                                <th style="width:80px;">Hình</th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Số lượng</th>
                                <th>Thành tiền</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ decimal tongtien = 0;}
                            @foreach (var cart in Model)
                            {
                                <tr>
                                    <td>@cart.ProductId</td>
                                    <td><img src="~/Public/images/products/@cart.Img" alt="@cart.Name" /></td>
                                    <td>@cart.Name</td>
                                    <td>@cart.Price VNĐ</td>
                                    <td>@cart.Qty</td>
                                    <td class="text-end">@string.Format("{0:0,0}", cart.Amount) VNĐ</td>
                                    <td class="text-center">
                                        <a class="text-danger" href="@Url.Action("CartDel", "Cart", new { productid = cart.ProductId })">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                                tongtien += cart.Amount;
                            }
                        </tbody>
                    </table>
                    <h3 style="font-size: 20px; font-weight: bold; ">Thông tin khách hàng</h3>
                    <div class="form-group my-2">
                        <label>Họ tên khách hàng</label>
                        <input name="FullName" readonly value="@user.FullName" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Email</label>
                        <input name="Email" readonly value="@user.Email" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Điện thoại</label>
                        <input name="Phone" readonly value="@user.Phone" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Điạ chỉ</label>
                        <input name="Address" readonly value="@user.Address" class="form-control" />
                    </div>
                    <h3 style="font-size: 20px; font-weight: bold; ">Thông tin người nhận</h3>
                    <div class="form-group my-2">
                        <label>Họ tên người nhận</label>
                        <input name="ReceiverName" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Email</label>
                        <input name="ReceiverEmail" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Điện thoại</label>
                        <input name="ReceiverPhone" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Điạ chỉ</label>
                        <input name="ReceiverAddress" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Ghi chú</label>
                        <textarea name="Note" class="form-control" rows="2"></textarea>
                    </div>
                    <button style="float: right; margin-left: 10px; " type="submit" class="btn btn-outline-success">Đặt mua</button>
                </div>
                <div class="col-md-3">
                    <h3 style="font-size: 20px; font-weight: bold; ">Thông tin</h3>
                    <p>Tổng tiền: @string.Format("{0:0,0}", tongtien) VNĐ</p>
                    <p>Tiền giảm: </p>
                </div>
            </div>

        </div>
    </div>
</section>
                                }

BanPC/Views/Cart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<div class="container my-3 "style="font-weight: bold;">
    <h2>Thanh toán thành công</h2>
    <a href="https://localhost:44312/">Mua thêm sản phẩm</a>
</div>